<a href="https://colab.research.google.com/github/kieranmcgregor/C/blob/master/Initial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import TensorFlow

In [62]:
import tensorflow as tf

Check TensorFlow version

In [63]:
print(tf.__version__)

2.4.1


Check Python version

In [64]:
from platform import python_version
print(python_version())

3.7.10


Initialization of Tensor

In [65]:
x = tf.constant(3)
print(x)

tf.Tensor(3, shape=(), dtype=int32)


In [66]:
x = tf.constant([[2, 3, 4], [4,5,6,]], dtype=tf.float32)
print(x)

tf.Tensor(
[[2. 3. 4.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


Creating N-dimensional Value

In [67]:
x = tf.ones((5,7),dtype=tf.float32)
print(x)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]], shape=(5, 7), dtype=float32)


In [68]:
x = tf.ones((5,),dtype=tf.float32)
print(x)

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32)


In [69]:
x = tf.zeros((3,3, 3),dtype=tf.float32)
print(x)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


Creating Identitiy Matrix

In [70]:
x = tf.eye(5, dtype=tf.int64)
print(x)

tf.Tensor(
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]], shape=(5, 5), dtype=int64)


In [71]:
#Creating array of random values

x = tf.random.uniform((5, 3),minval = 1, maxval=100, dtype=tf.int64)
print(x)

tf.Tensor(
[[10 10 36]
 [48 48 77]
 [31 99 80]
 [ 1 67 90]
 [72 20 49]], shape=(5, 3), dtype=int64)


In [72]:
x = tf.random.normal((3,3,3))
print(x)

tf.Tensor(
[[[ 1.3197495  -0.6333427   0.33242777]
  [-0.1619738  -0.7560965  -1.0209843 ]
  [-0.8411585  -1.556381    2.8021472 ]]

 [[ 0.27379218  0.7968468  -1.0636035 ]
  [ 0.7333488  -1.4382119   0.26776454]
  [ 1.4037865   1.8115947  -0.6018658 ]]

 [[-1.7049814   0.07835011  0.9673544 ]
  [ 0.45663476 -0.7754563  -0.41995084]
  [ 1.2108089   1.0777223  -0.6935262 ]]], shape=(3, 3, 3), dtype=float32)


In [73]:
x = tf.linspace(0,10,5)
print(x)

tf.Tensor([ 0.   2.5  5.   7.5 10. ], shape=(5,), dtype=float64)


In [74]:
x = tf.range(start=0, limit=10, delta=3)
print(x)
x=tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0 3 6 9], shape=(4,), dtype=int32)
tf.Tensor([0. 3. 6. 9.], shape=(4,), dtype=float32)


Mathematical Operations

In [78]:
a = tf.constant([[1,2,3],[95,0,6]])
b = tf.constant([[4,5,6],[1,2,3]])
z = a + b
print(z)
z=tf.add(a,b)
print(z)
z = a - b
print(z)

tf.Tensor(
[[ 5  7  9]
 [96  2  9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 5  7  9]
 [96  2  9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-3 -3 -3]
 [94 -2  3]], shape=(2, 3), dtype=int32)


Dot Product

In [81]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

# Inner product
z = tf.tensordot(a,b,axes=1)
print(z)

# Outer product
z = tf.tensordot(a,b,axes=0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]], shape=(3, 3), dtype=int32)


Matrix Multiplication

In [83]:
a = tf.random.normal((2,3))
b = tf.random.normal((3,2))
z = tf.matmul(a, b)
print(z)
z = a@b
print(z)

tf.Tensor(
[[ 1.9672446  1.5347931]
 [-2.5563986  1.9263031]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.9672446  1.5347931]
 [-2.5563986  1.9263031]], shape=(2, 2), dtype=float32)


Indexing

In [84]:
x = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [87]:
print(x[1,0])

tf.Tensor(4, shape=(), dtype=int32)


In [89]:
print(x[1:,0:2])

tf.Tensor(
[[4 5]
 [7 8]], shape=(2, 2), dtype=int32)


In [96]:
x = tf.constant([0,4,2,5,7,8,90,10])
print(x)
print(x[2:4])
print(x[::3])
print(x[-1::-3])

tf.Tensor([ 0  4  2  5  7  8 90 10], shape=(8,), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor([ 0  5 90], shape=(3,), dtype=int32)
tf.Tensor([10  7  4], shape=(3,), dtype=int32)


Reshaping

In [97]:
x = tf.range(6)
print(x)
x = tf.reshape(x,(3,2))
print(x)

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)


In [99]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 2 4]
 [1 3 5]], shape=(2, 3), dtype=int32)


Testing GitHub

In [105]:
print("Hello github")
x = [[2,3,4,5],[6,5,4,3]]
print(x[1][3])
x = tf.constant([[2,3,4,5],[6,5,4,3]])
print(x[1,3])

Hello github
3
tf.Tensor(3, shape=(), dtype=int32)


Testing HotKeys

In [106]:
print("Can you here me now?")

Can you here me now?
